version: '3.8'

services:
  redis-server:
    image: redis:7-alpine
    container_name: redis-courier-cache
    networks:
      - global-microservices-net

  courier-service:
    build: ./ms-courier-service
    image: ms-courier-service:latest
    container_name: ms-courier-service-container
    ports:
      - "9001:9001"
    environment:
      - SERVER_PORT=9001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/courier_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - REDIS_HOST=redis-server
      - SPRING_RABBITMQ_HOST=rabbitmq-server
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq-server:
        condition: service_started
      redis-server:
        condition: service_started
    networks:
      - global-microservices-net

  postgres-db:
    image: postgres:15
    container_name: courier_db
    environment:
      - POSTGRES_DB=courier_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d courier_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - global-microservices-net

  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - global-microservices-net

networks:
  global-microservices-net:
    external: true